### ISSUE TITLE
Tree Sitter - SuperHTML (.shtml) Syntax Highlighting for Neovim, ...

### ISSUE THREAD

**Issue by kristoff-it** [kristoff-it/superhtml#25]
In `tree-sitter-superhtml` there's a grammar for SuperHTML templates that can be used by any editor (or tool in general) that relies on Tree Sitter.

Unfortunately, a grammar alone is not enough to get syntax highlighting in an editor, as you also need highlighting queries, and those need to be crafted for each editor.

I've developed the current queries for Helix and they look like this:

![CleanShot 2024-07-27 at 09 14 03](https://github.com/user-attachments/assets/29f0db29-6135-4c85-84f9-aefeb42a21e6)

Notice in particular how id values of block definitions are underlined differently from other non-semantically-relevant(to the templating engine) ids.

Trying yesterday with a user to add those same queries to Neovim caused an error, which means that Neovim users at the moment cannot have syntax highlighting for .shtml files.

**Comment by TurtleWilly** [comment]
Just a side note: `.shtml` is a very well known extensions for HTML files with support for Server Side Includes (SSI), see: https://en.wikipedia.org/wiki/Server_Side_Includes

It may be smart to use a different default extension for "SuperHTML" to avoid confusion.

**Comment by kristoff-it** [comment]
This has been working for a while now, forgot to close this issue.

The name can stay, [Vim knows how to detect](https://github.com/vim/vim/pull/15367) the correct file type and other editors can figure out too (and some of them don't even have support for SSI anymore).
