### ISSUE TITLE
"super" command already exists

### ISSUE THREAD

**Issue by Flimm** [kristoff-it/superhtml#27]
I just wanted to let you know that the `super` command already exists. Although it is not installed by default, it is available from the Debian and Ubuntu repositories (and possibly other distros), from [the package `super`](https://packages.ubuntu.com/noble/super). Here is its description:

>Description: Execute commands setuid root
>
> Super allows specified users to execute scripts (or other commands) as if they were root; or it can set the uid and/or gid on a per-command basis before executing the command.  It is intended to be a secure alternative to making scripts setuid root.

Consider renaming the executable to `superhtml`. Users who want a shorter command can easily create an alias in their favourite shell. One day, this software may get packaged for Debian, and the Debian maintainer may rename the executable for you to prevent conflicts, which may prove confusing to users following upstream documentation. This is just a suggestion, I won't be upset if you decide to keep the command name the same.

**Comment by kristoff-it** [comment]
I actually renamed it to `superhtml` a while ago, forgot to update the example in the readme.

**Comment by Flimm** [comment]
Ah great! I hadn't tried the command yet, so I didn't notice that.

The usage section in the README.md file still says `super` instead of `superhtml`, here:

```
$ superhtml
Usage: super COMMAND [OPTIONS]
```

I also noticed that the output of the `superhtml` command also has this problem in the latest release, so it's not just a problem in the documentation.

**Comment by wong-justin** [comment]
The last line of the README also seems to show some naming inconsistencies:

> `tail -f ~/.cache/super/super.log`

I have `~/.cache/super/` and `~/.cache/superhtml.log` after running `superhtml v0.5.0`.
