### ISSUE TITLE
`"editor.formatOnSave": false` is not respected

### ISSUE THREAD

**Issue by MarkTiedemann** [kristoff-it/superhtml#33]
See title.

I'd like to trigger formatting manually, not on save.

**Comment by MarkTiedemann** [comment]
Why would this extension override the default setting?

I tried `"[superhtml]": { "editor.formatOnSave": false }`, but it didn't work.

Only with the `[html]` block, it seems to not format on save.

Then again, I'd argue this shouldn't be the default.

**Comment by dubrowgn** [comment]
@kristoff-it I also ran head long into this, and figuring out how to get it to stop is not straight forward. It's pretty frustrating to have to revisit this setting every time you add a new plug-in. Is there a rationale for why the extension should not obey the global setting?
