### ISSUE TITLE
SuperHTML crashes when emmet wraps with abbriviation (Neovim)

### ISSUE THREAD

**Issue by johannesrld** [kristoff-it/superhtml#38]
when wrapping some tag with emmets "wrap with abbreviation" feature (provided by [olrtg/nvim-emmet](https://github.com/olrtg/nvim-emmet)) superHTML crashes, with nothing logged to LSP's log file

**Comment by kristoff-it** [comment]
Please provide some repro steps, without those it's impossible for me to know what's going on. Note that I'm not a VSCode user so the more detailed your steps, the better the chances I will be able to reproduce your crash. 

If I can't reproduce the crash, I won't be able to fix your bug.

**Comment by kristoff-it** [comment]
Closing, if you find a way to reproduce the error, either add a comment here or open a new issue.
