### ISSUE TITLE
formatter: incorrect alignment in some cases

### ISSUE THREAD

**Issue by Atomk** [kristoff-it/superhtml#40]
This is from the file `base.shtml` from the [ziglang.org repo](https://github.com/ziglang/www.ziglang.org/blob/main/layouts/templates/base.shtml).

This is the correct alignment, before saving:
![image](https://github.com/user-attachments/assets/893e6b4d-e6d3-410a-a04f-0ec1b3e10583)

This is after saving, autoformatted by the SuperHTML plugin:
![image](https://github.com/user-attachments/assets/a6ff688b-038b-4bc1-b9b0-4338d6241903)

This also causes issues with code folding, as you can see with the icons on the left.
From a quick look it seems to happen with [void elements](https://developer.mozilla.org/en-US/docs/Glossary/Void_element) (no closing tag) when attributes are spread over multiple lines.

**Comment by EmDash00** [comment]
I'm also getting this issue in Neovim.

**Comment by Artemia76** [comment]
Same for me
![image](https://github.com/user-attachments/assets/869bdbec-1455-412a-bb27-70950a010864)

**Comment by kristoff-it** [comment]
This is fixed in SuperHTML v0.5.1.

The update has also been pushed on the VSCode marketplace (and Open VSX), so it should update automatically.

**Comment by Atomk** [comment]
Thank you for working on this, unfortunately I tested with version v0.5.2 and the example I've shown in the first screenshot now becomes this:
![image](https://github.com/user-attachments/assets/a2b9145a-21d4-428c-9f4d-df46208d351f)

**Comment by Artemia76** [comment]
same here :
![image](https://github.com/user-attachments/assets/8ff81779-4be2-4b84-b4da-d068acaeecdf)

**Comment by kristoff-it** [comment]
Whoops! Pushed a fix now.
