### ISSUE TITLE
'html_elements_cant_self_close' notice for 'figure' element

### ISSUE THREAD

**Issue by lazysoundsystem** [kristoff-it/superhtml#43]
Just trying out superhtml, so may be I'm misunderstanding something.

Checking an html file gives me `html_elements_cant_self_close` for the opening of each `<figure>` element. I tried with the code snippet from https://developer.mozilla.org/docs/Web/HTML/Element/figure and it gave the same message.

Version 0.5.0

**Comment by kristoff-it** [comment]
The `<img>` element in that code snippet ends with a self-closing `/`, that's what SuperHTML is complaining about. `img` is a void tag and naturally ends with a simple `>`.

**Comment by lazysoundsystem** [comment]
Thanks - I got confused as the line number given was for the 'figure' tag. Will look beyond that next time. Nice to know.

(I note that the snippet given for <img> also fails here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img )

**Comment by niklaskorz** [comment]
The current behavior of superhtml is not compliant with the HTML5 spec:

https://html.spec.whatwg.org/multipage/syntax.html#start-tags

> Then, if the element is one of the [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), or if the element is a [foreign element](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), **then there may be a single U+002F SOLIDUS character (/)**, which on [foreign elements](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements) marks the start tag as self-closing. On [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements), it does not mark the start tag as self-closing but instead is unnecessary and **has no effect of any kind**. For such void elements, it should be used only with caution — especially since, if directly preceded by an [unquoted attribute value](https://html.spec.whatwg.org/multipage/syntax.html#unquoted), it becomes part of the attribute value rather than being discarded by the parser.
