### ISSUE TITLE
`Cannot find super in PATH`

### ISSUE THREAD

**Issue by inspector71** [kristoff-it/superhtml#51]
Fresh first time installation produces this error:

`Cannot find super in PATH`

**Comment by kristoff-it** [comment]
Which editor are you using? VSCode?

**Comment by inspector71** [comment]
Apologies for the lack of detail. 

Yes, VS Code running on Windows 10.

**Comment by kristoff-it** [comment]
Update your vscode and the superhtml extension. Recent versions of the extension don't even try to find any executable on your system.
